REMOTE_NAME = 'frigidaireAC'

KEY_POWER = 'KEY_POWER'
KEY_UP = 'KEY_UP'
KEY_DOWN = 'KEY_DOWN'
KEY_LEFT = 'KEY_LEFT'
KEY_RIGHT = 'KEY_RIGHT'

VALID_KEYS = [KEY_POWER, KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT]


CHANNEL_SUBSCRIBE = 'remote'
CHANNEL_PUBLISH = 'ack'
